from enum import IntEnum


class StatusWord(IntEnum):
    """Status words used by the Cardano app.

    The ISO/IEC 7816-4 (SDK) words appear first, followed by Cardano-specific extensions.
    """

    # SDK status words (standard ISO/IEC 7816-4)
    SWO_COMMAND_NOT_ALLOWED = 0x6980
    SWO_SECURITY_CONDITION_NOT_SATISFIED = 0x6982
    SWO_CONDITIONS_NOT_SATISFIED = 0x6985
    SWO_INCORRECT_P1_P2 = 0x6A86
    SWO_WRONG_DATA_LENGTH = 0x6A87
    SWO_INVALID_INS = 0x6D00
    SWO_INVALID_CLA = 0x6E00
    SWO_INVALID_DATA = 0x6E07
    SWO_SUCCESS = 0x9000

    # Cardano-specific status words (0x6BXX range - ISO 7816-4 compliant)
    SWO_WRONG_RESPONSE_LENGTH = 0xB000  # Legacy, kept for compatibility
    SWO_INVALID_TX_LENGTH = 0x6B00
    SWO_TX_PARSING_FAIL = 0x6B01
    SWO_WRONG_TX_INIT_APDU_DATA = 0x6B02
    SWO_BAD_STATE = 0x6B03
    SWO_SIGNATURE_FAIL = 0x6B04
    SWO_BIP44_PATH_PARSING_FAIL = 0x6B05
    SWO_OPCERT_PARSING_FAIL_KES_KEY = 0x6B10
    SWO_OPCERT_PARSING_FAIL_KES_PERIOD = 0x6B11
    SWO_OPCERT_PARSING_FAIL_ISSUE_COUNTER = 0x6B12
    SWO_OPCERT_PARSING_FAIL_POOL_KEY_PATH = 0x6B13
    SWO_INVALID_OPCERT_LENGTH = 0x6B14

    # Transaction body field errors (organized by CBOR key: error = 0x6B20 + CBOR_KEY)
    SWO_TX_PARSING_FAIL_INPUTS = 0x6B20
    SWO_TX_PARSING_FAIL_OUTPUTS = 0x6B21
    SWO_TX_PARSING_FAIL_FEE = 0x6B22
    SWO_TX_PARSING_FAIL_TTL = 0x6B23
    SWO_TX_PARSING_FAIL_CERTIFICATES = 0x6B24
    SWO_TX_PARSING_FAIL_WITHDRAWALS = 0x6B25
    SWO_TX_PARSING_FAIL_AUX_DATA_HASH = 0x6B27
    SWO_TX_PARSING_FAIL_VALIDITY_INTERVAL_START = 0x6B28
    SWO_TX_PARSING_FAIL_MINT = 0x6B29
    SWO_TX_PARSING_FAIL_SCRIPT_DATA_HASH = 0x6B2B
    SWO_TX_PARSING_FAIL_COLLATERAL_INPUTS = 0x6B2D
    SWO_TX_PARSING_FAIL_REQUIRED_SIGNERS = 0x6B2E
    SWO_TX_PARSING_FAIL_COLLATERAL_OUTPUT = 0x6B30
    SWO_TX_PARSING_FAIL_TOTAL_COLLATERAL = 0x6B31
    SWO_TX_PARSING_FAIL_REFERENCE_INPUTS = 0x6B32
    SWO_TX_PARSING_FAIL_VOTING_PROCEDURES = 0x6B33
    SWO_TX_PARSING_FAIL_TREASURY = 0x6B35
    SWO_TX_PARSING_FAIL_DONATION = 0x6B36
    # Network/Protocol validation errors
    SWO_INVALID_NETWORK_ID = 0x6B37
    SWO_INVALID_PROTOCOL_MAGIC = 0x6B38
    # Transaction structure errors
    SWO_TX_PARSING_FAIL_INCLUSION_FLAG = 0x6B39
    SWO_TX_PARSING_FAIL_BUFFER_NOT_FULLY_CONSUMED = 0x6B3A
    SWO_TX_PARSING_FAIL_CANONICAL_ORDER = 0x6B3B
