from enum import IntEnum


class StatusWord(IntEnum):
    """Status words used by the Cardano app.

    The ISO/IEC 7816-4 (SDK) words appear first, followed by Cardano-specific extensions.
    """

    # SDK status words (standard ISO/IEC 7816-4)
    SWO_COMMAND_NOT_ALLOWED = 0x6980
    SWO_SECURITY_CONDITION_NOT_SATISFIED = 0x6982
    SWO_CONDITIONS_NOT_SATISFIED = 0x6985
    SWO_INCORRECT_P1_P2 = 0x6A86
    SWO_WRONG_DATA_LENGTH = 0x6A87
    SWO_INVALID_INS = 0x6D00
    SWO_INVALID_CLA = 0x6E00
    SWO_INVALID_DATA = 0x6E07
    SWO_SUCCESS = 0x9000

    # Cardano-specific status words (0xB0XX range)
    SWO_WRONG_RESPONSE_LENGTH = 0xB000
    SWO_INVALID_TX_LENGTH = 0xB004
    SWO_TX_PARSING_FAIL = 0xB005
    SWO_WRONG_TX_INIT_APDU_DATA = 0xB006
    SWO_BAD_STATE = 0xB007
    SWO_SIGNATURE_FAIL = 0xB008
    SWO_OPCERT_PARSING_FAIL_KES_KEY = 0xB010
    SWO_OPCERT_PARSING_FAIL_KES_PERIOD = 0xB011
    SWO_OPCERT_PARSING_FAIL_ISSUE_COUNTER = 0xB012
    SWO_OPCERT_PARSING_FAIL_POOL_KEY_PATH = 0xB013
    SWO_INVALID_OPCERT_LENGTH = 0xB014
    SWO_BIP44_PATH_PARSING_FAIL = 0xB015

    # Transaction body field errors (organized by CBOR key)
    SWO_TX_PARSING_FAIL_INPUTS = 0xB020
    SWO_TX_PARSING_FAIL_OUTPUTS = 0xB021
    SWO_TX_PARSING_FAIL_FEE = 0xB022
    SWO_TX_PARSING_FAIL_TTL = 0xB023
    SWO_TX_PARSING_FAIL_CERTIFICATES = 0xB024
    SWO_TX_PARSING_FAIL_WITHDRAWALS = 0xB025
    SWO_TX_PARSING_FAIL_AUX_DATA_HASH = 0xB027
    SWO_TX_PARSING_FAIL_VALIDITY_INTERVAL_START = 0xB028
    SWO_TX_PARSING_FAIL_MINT = 0xB029
    SWO_TX_PARSING_FAIL_SCRIPT_DATA_HASH = 0xB02B
    SWO_TX_PARSING_FAIL_COLLATERAL_INPUTS = 0xB02D
    SWO_TX_PARSING_FAIL_REQUIRED_SIGNERS = 0xB02E
    SWO_TX_PARSING_FAIL_COLLATERAL_OUTPUT = 0xB030
    SWO_TX_PARSING_FAIL_TOTAL_COLLATERAL = 0xB031
    SWO_TX_PARSING_FAIL_REFERENCE_INPUTS = 0xB032
    SWO_TX_PARSING_FAIL_VOTING_PROCEDURES = 0xB033
    SWO_TX_PARSING_FAIL_TREASURY = 0xB035
    SWO_TX_PARSING_FAIL_DONATION = 0xB036
    # Network/Protocol validation errors
    SWO_INVALID_NETWORK_ID = 0xB037
    SWO_INVALID_PROTOCOL_MAGIC = 0xB038
    # Transaction structure errors
    SWO_TX_PARSING_FAIL_INCLUSION_FLAG = 0xB039
    SWO_TX_PARSING_FAIL_BUFFER_NOT_FULLY_CONSUMED = 0xB03A
    SWO_TX_PARSING_FAIL_CANONICAL_ORDER = 0xB03B
    # UI errors
    SWO_UI_PAIRS_EXCEED_CAPABILITY = 0xB03C
