from enum import IntEnum


class StatusWord(IntEnum):
    """Status words used by the Cardano app.

    The ISO/IEC 7816-4 (SDK) words appear first, followed by Cardano-specific extensions.
    """

    # SDK status words (standard ISO/IEC 7816-4)
    SWO_COMMAND_NOT_ALLOWED = 0x6980
    SWO_SECURITY_CONDITION_NOT_SATISFIED = 0x6982
    SWO_CONDITIONS_NOT_SATISFIED = 0x6985
    SWO_INCORRECT_P1_P2 = 0x6A86
    SWO_WRONG_DATA_LENGTH = 0x6A87
    SWO_INVALID_INS = 0x6D00
    SWO_INVALID_CLA = 0x6E00
    SWO_INVALID_DATA = 0x6E07
    SWO_SUCCESS = 0x9000

    # Cardano-specific status words (0xB0XX range)
    SWO_WRONG_RESPONSE_LENGTH = 0xB000
    SWO_DISPLAY_BIP32_PATH_FAIL = 0xB001
    SWO_DISPLAY_ADDRESS_FAIL = 0xB002
    SWO_DISPLAY_AMOUNT_FAIL = 0xB003
    SWO_DISPLAY_UI_FAIL = 0xB006
    SWO_INVALID_TX_LENGTH = 0xB004
    SWO_TX_PARSING_FAIL = 0xB005
    SWO_BAD_STATE = 0xB007
    SWO_SIGNATURE_FAIL = 0xB008
    SWO_OPCERT_PARSING_FAIL = 0xB011
    SWO_INVALID_OPCERT_LENGTH = 0xB012
    SWO_BIP44_PATH_PARSING_FAIL = 0xB013
    SWO_TX_PARSING_FAIL_INPUTS = 0xB020
    SWO_TX_PARSING_FAIL_OUTPUTS = 0xB021
    SWO_TX_PARSING_FAIL_FEE = 0xB022
    SWO_TX_PARSING_FAIL_TTL = 0xB023
    SWO_TX_PARSING_FAIL_INCLUSION_FLAG = 0xB024
    SWO_INVALID_NETWORK_ID = 0xB025
    SWO_TX_PARSING_FAIL_VALIDITY_INTERVAL_START = 0xB026
    SWO_TX_PARSING_FAIL_BUFFER_NOT_FULLY_CONSUMED = 0xB027
    SWO_INVALID_PROTOCOL_MAGIC = 0xB028
