# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: 2024 Ledger SAS
# SPDX-License-Identifier: LicenseRef-LEDGER
"""
This module provides Ragger tests for Address check
"""

from typing import List, Optional
from dataclasses import dataclass

from ragger.navigator import NavInsID

from application_client.app_def import NetworkDesc, AddressType, Mainnet, Testnet, FakeNet


@dataclass
class DeriveAddressTestCase:
    name: str
    netDesc: NetworkDesc
    addrType: AddressType
    spendingValue: str      # spending path or keyHash
    stakingValue: str = ""  # staking path or keyHash
    result: Optional[str] = ""
    nano_nav_confirm: Optional[List[NavInsID]] = None  # list of specific navigation instructions for Nano
    nano_nav_show: Optional[List[NavInsID]] = None  # list of specific navigation instructions for Nano


def pointer_to_str(blockIndex: int, txIndex: int, certificateIndex: int) -> str:
    data: str = ""
    data += f"{blockIndex.to_bytes(4, 'big').hex()}"
    data += f"{txIndex.to_bytes(4, 'big').hex()}"
    data += f"{certificateIndex.to_bytes(4, 'big').hex()}"
    return data


# pylint: disable=line-too-long
byronTestCases = [
    DeriveAddressTestCase("Mainnet_1",
                  Mainnet,
                  AddressType.BYRON,
                  "m/44'/1815'/1'/0/55'"),
    DeriveAddressTestCase("Mainnet_2",
                  Mainnet,
                  AddressType.BYRON,
                  "m/44'/1815'/1'/0/12'"),
    DeriveAddressTestCase("Mainnet_3",
                  Mainnet,
                  AddressType.BYRON,
                  "m/44'/1815'/101'/0/12'"),
    DeriveAddressTestCase("Mainnet_4",
                  Mainnet,
                  AddressType.BYRON,
                  "m/44'/1815'/0'/0/1000001'"),
    DeriveAddressTestCase("Testnet_1",
                  Testnet,
                  AddressType.BYRON,
                  "m/44'/1815'/1'/0/12'",
                  result="2657WMsDfac5679tC5DgShwENgGLwAuGNanDjDaCzuEEqXDsP6i2345FcVkwRYVqX"),
]


rejectTestCases = [
    DeriveAddressTestCase("path_too_short",
             Mainnet,
             AddressType.BYRON,
             "m/44'/1815'/1'"),
    DeriveAddressTestCase("invalid_path",
             Mainnet,
             AddressType.BYRON,
             "m/44'/1815'/1'/5/10'"),
    DeriveAddressTestCase("Byron_with_Shelley_path",
             Mainnet,
             AddressType.BYRON,
             "m/1852'/1815'/1'/0/10"),
    DeriveAddressTestCase("base_keykey_with_Byron_spending_path",
             Mainnet,
             AddressType.BASE_PAYMENT_KEY_STAKE_KEY,
             "m/44'/1815'/1'/0/1",
             "m/1852'/1815'/1'/2/0"),
    DeriveAddressTestCase("base_keykey_with_wrong_spending_path",
             Mainnet,
             AddressType.BASE_PAYMENT_KEY_STAKE_KEY,
             "m/1852'/1815'/1'/2/0",
             "m/1852'/1815'/1'/2/0"),
    DeriveAddressTestCase("base_keykey_with_wrong_staking_path_1",
             Mainnet,
             AddressType.BASE_PAYMENT_KEY_STAKE_KEY,
             "m/1852'/1815'/1'/0/0",
             "m/1852'/1815'/1'/0/1"),
    DeriveAddressTestCase("base_keyscript_with_Byron_spending_path",
             Mainnet,
             AddressType.BASE_PAYMENT_KEY_STAKE_SCRIPT,
             "m/44'/1815'/1'/0/1",
             "222a946b9ad3d2ddf029d3a828f0468aece76895f15c9efbd69b4277"),
    DeriveAddressTestCase("base_address_scripthashkeyhash_not_allowed",
             Mainnet,
             AddressType.BASE_PAYMENT_SCRIPT_STAKE_KEY,
             "122a946b9ad3d2ddf029d3a828f0468aece76895f15c9efbd69b4277",
             "222a946b9ad3d2ddf029d3a828f0468aece76895f15c9efbd69b4277"),
    DeriveAddressTestCase("pointer_with_Byron_spending_path",
             Mainnet,
             AddressType.POINTER_KEY,
             "m/44'/1815'/1'/0/0",
             pointer_to_str(1, 2, 3)),
    DeriveAddressTestCase("pointer_with_wrong_spending_path",
             Mainnet,
             AddressType.POINTER_KEY,
             "m/1852'/1815'/1'/2/0",
             pointer_to_str(1, 2, 3)),
    DeriveAddressTestCase("enterprise_with_Byron_spending_path",
             Mainnet,
             AddressType.ENTERPRISE_KEY,
             "m/44'/1815'/1'/0/0"),
    DeriveAddressTestCase("enterprise_with_wrong_spending_path",
             Mainnet,
             AddressType.ENTERPRISE_KEY,
             "m/1852'/1815'/1'/2/0"),
]


shelleyTestCasesNoConfirm = [
    DeriveAddressTestCase("base_address_pathpath_1",
                    FakeNet,
                    AddressType.BASE_PAYMENT_KEY_STAKE_KEY,
                    "m/1852'/1815'/0'/0/1",
                    "m/1852'/1815'/0'/2/0",
                    nano_nav_show=[NavInsID.BOTH_CLICK] * 2 + [NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] * 2),
    DeriveAddressTestCase("base_address_pathpath_2",
                    Testnet,
                    AddressType.BASE_PAYMENT_KEY_STAKE_KEY,
                    "m/1852'/1815'/0'/0/1",
                    "m/1852'/1815'/0'/2/0",
                    nano_nav_show=[NavInsID.BOTH_CLICK] * 2 + [NavInsID.RIGHT_CLICK] * 2 + [NavInsID.BOTH_CLICK] * 2),
    DeriveAddressTestCase("base_address_pathpath_multidelegation_stake_key_usual",
                    Testnet,
                    AddressType.BASE_PAYMENT_KEY_STAKE_KEY,
                    "m/1852'/1815'/0'/0/1",
                    "m/1852'/1815'/0'/2/60",
                    nano_nav_show=[NavInsID.BOTH_CLICK] * 2 + [NavInsID.RIGHT_CLICK] * 2 + [NavInsID.BOTH_CLICK] * 2),
    DeriveAddressTestCase("base_address_pathkeyHash_1",
                    Testnet,
                    AddressType.BASE_PAYMENT_KEY_STAKE_KEY,
                    "m/1852'/1815'/0'/0/1",
                    "1d227aefa4b773149170885aadba30aab3127cc611ddbc4999def61c",
                    nano_nav_show=[NavInsID.BOTH_CLICK] + [NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] + [NavInsID.RIGHT_CLICK] * 2 + [NavInsID.BOTH_CLICK] * 2),
    DeriveAddressTestCase("base_address_pathkeyHash_2",
                    FakeNet,
                    AddressType.BASE_PAYMENT_KEY_STAKE_KEY,
                    "m/1852'/1815'/0'/0/1",
                    "122a946b9ad3d2ddf029d3a828f0468aece76895f15c9efbd69b4277",
                    nano_nav_show=[NavInsID.BOTH_CLICK] + [NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] + [NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] * 2),
    DeriveAddressTestCase("base_address_scriptHashpath",
                    FakeNet,
                    AddressType.BASE_PAYMENT_SCRIPT_STAKE_KEY,
                    "122a946b9ad3d2ddf029d3a828f0468aece76895f15c9efbd69b4277",
                    "m/1852'/1815'/0'/2/0",
                    nano_nav_show=[NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] * 2 + [NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] * 2),
    DeriveAddressTestCase("base_address_scriptHashpath_multidelegation",
                    FakeNet,
                    AddressType.BASE_PAYMENT_SCRIPT_STAKE_KEY,
                    "122a946b9ad3d2ddf029d3a828f0468aece76895f15c9efbd69b4277",
                    "m/1852'/1815'/0'/2/3",
                    nano_nav_show=[NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] * 2 + [NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] * 2),
    DeriveAddressTestCase("base_address_pathscriptHash",
                    FakeNet,
                    AddressType.BASE_PAYMENT_KEY_STAKE_SCRIPT,
                    "m/1852'/1815'/0'/0/1",
                    "122a946b9ad3d2ddf029d3a828f0468aece76895f15c9efbd69b4277",
                    nano_nav_show=[NavInsID.BOTH_CLICK] + [NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] + [NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] * 2),
    DeriveAddressTestCase("base_address_scriptHashscriptHash",
                    FakeNet,
                    AddressType.BASE_PAYMENT_SCRIPT_STAKE_SCRIPT,
                    "122a946b9ad3d2ddf029d3a828f0468aece76895f15c9efbd69b4277",
                    "122a946b9ad3d2ddf029d3a828f0468aece76895f15c9efbd69b4277",
                    nano_nav_show=[NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] + [NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] + [NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] * 2),
    DeriveAddressTestCase("enterprise_path_1",
                    Testnet,
                    AddressType.ENTERPRISE_KEY,
                    "m/1852'/1815'/0'/0/1",
                    nano_nav_show=[NavInsID.BOTH_CLICK] * 2 + [NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] * 2),
    DeriveAddressTestCase("enterprise_path_2",
                    FakeNet,
                    AddressType.ENTERPRISE_KEY,
                    "m/1852'/1815'/0'/0/1",
                    nano_nav_show=[NavInsID.BOTH_CLICK] * 2 + [NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] * 2),
    DeriveAddressTestCase("enterprise_script_1",
                    Testnet,
                    AddressType.ENTERPRISE_SCRIPT,
                    "122a946b9ad3d2ddf029d3a828f0468aece76895f15c9efbd69b4277",
                    nano_nav_show=[NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] * 2 + [NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] * 2),
    DeriveAddressTestCase("enterprise_script_2",
                    FakeNet,
                    AddressType.ENTERPRISE_SCRIPT,
                    "122a946b9ad3d2ddf029d3a828f0468aece76895f15c9efbd69b4277",
                    nano_nav_show=[NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] * 2 + [NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] * 2),
    DeriveAddressTestCase("pointer_path_1",
                    Testnet,
                    AddressType.POINTER_KEY,
                    "m/1852'/1815'/0'/0/1",
                    pointer_to_str(1, 2, 3),
                    nano_nav_show=[NavInsID.BOTH_CLICK] * 2 + [NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] * 2),
    DeriveAddressTestCase("pointer_path_2",
                    FakeNet,
                    AddressType.POINTER_KEY,
                    "m/1852'/1815'/0'/0/1",
                    pointer_to_str(24157, 177, 42),
                    nano_nav_show=[NavInsID.BOTH_CLICK] * 2 + [NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] * 2),
    DeriveAddressTestCase("pointer_path_3",
                    FakeNet,
                    AddressType.POINTER_KEY,
                    "m/1852'/1815'/0'/0/1",
                    pointer_to_str(0, 0, 0),
                    nano_nav_show=[NavInsID.BOTH_CLICK] * 2 + [NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] * 2),
    DeriveAddressTestCase("pointer_script_1",
                    Testnet,
                    AddressType.POINTER_SCRIPT,
                    "122a946b9ad3d2ddf029d3a828f0468aece76895f15c9efbd69b4277",
                    pointer_to_str(1, 2, 3),
                    nano_nav_show=[NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] * 2 + [NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] * 2),
    DeriveAddressTestCase("pointer_script_2",
                    FakeNet,
                    AddressType.POINTER_SCRIPT,
                    "122a946b9ad3d2ddf029d3a828f0468aece76895f15c9efbd69b4277",
                    pointer_to_str(24157, 177, 42),
                    nano_nav_show=[NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] * 2 + [NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] * 2),
    DeriveAddressTestCase("pointer_script_3",
                    FakeNet,
                    AddressType.POINTER_SCRIPT,
                    "122a946b9ad3d2ddf029d3a828f0468aece76895f15c9efbd69b4277",
                    pointer_to_str(0, 0, 0),
                    nano_nav_show=[NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] * 2 + [NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] * 2),
    DeriveAddressTestCase("reward_path_1",
                    Testnet,
                    AddressType.REWARD_KEY,
                    "",
                    "m/1852'/1815'/0'/2/0",
                    nano_nav_show=[NavInsID.BOTH_CLICK] + [NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] * 2),
    DeriveAddressTestCase("reward_path_2",
                    FakeNet,
                    AddressType.REWARD_KEY,
                    "",
                    "m/1852'/1815'/0'/2/0",
                    nano_nav_show=[NavInsID.BOTH_CLICK] + [NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] * 2),
    DeriveAddressTestCase("reward_multidelegation_usual",
                    Testnet,
                    AddressType.REWARD_KEY,
                    "",
                    "m/1852'/1815'/0'/2/1",
                    nano_nav_show=[NavInsID.BOTH_CLICK] + [NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] * 2),
    DeriveAddressTestCase("reward_script_1",
                    Testnet,
                    AddressType.REWARD_SCRIPT,
                    "",
                    "122a946b9ad3d2ddf029d3a828f0468aece76895f15c9efbd69b4277",
                    nano_nav_show=[NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] + [NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] * 2),
    DeriveAddressTestCase("reward_script_2",
                    FakeNet,
                    AddressType.REWARD_SCRIPT,
                    "",
                    "122a946b9ad3d2ddf029d3a828f0468aece76895f15c9efbd69b4277",
                    nano_nav_show=[NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] + [NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] * 2),
]

nav_inst_1 = [NavInsID.BOTH_CLICK] * 3 + [NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] * 2
nav_inst_2 = [NavInsID.BOTH_CLICK] * 2 + [NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] * 3

shelleyTestCasesWithConfirm = [
    DeriveAddressTestCase("base_address_pathpath_unusual_spending_path_account",
                    FakeNet,
                    AddressType.BASE_PAYMENT_KEY_STAKE_KEY,
                    "m/1852'/1815'/101'/0/1",
                    "m/1852'/1815'/0'/2/0",
                    nano_nav_show=[NavInsID.BOTH_CLICK] * 3 + [NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] * 2),
    DeriveAddressTestCase("base_address_pathpath_unusual_spending_path_address_index",
                    FakeNet,
                    AddressType.BASE_PAYMENT_KEY_STAKE_KEY,
                    "m/1852'/1815'/1'/0/1000001",
                    "m/1852'/1815'/0'/2/0",
                    nano_nav_show=[NavInsID.BOTH_CLICK] * 3 + [NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] * 2),
    DeriveAddressTestCase("base_address_pathpath_unusual_staking_path_account",
                    FakeNet,
                    AddressType.BASE_PAYMENT_KEY_STAKE_KEY,
                    "m/1852'/1815'/10'/0/4",
                    "m/1852'/1815'/101'/2/0",
                    nano_nav_show=[NavInsID.BOTH_CLICK] * 3 + [NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] * 2),
    DeriveAddressTestCase("base_address_pathpath_multidelegation_stake_key_unusual_account",
                    FakeNet,
                    AddressType.BASE_PAYMENT_KEY_STAKE_KEY,
                    "m/1852'/1815'/0'/0/1",
                    "m/1852'/1815'/101'/2/60",
                    nano_nav_show=[NavInsID.BOTH_CLICK] * 3 + [NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] * 2),
    DeriveAddressTestCase("base_address_pathpath_multidelegation_stake_key_unusual_index",
                    FakeNet,
                    AddressType.BASE_PAYMENT_KEY_STAKE_KEY,
                    "m/1852'/1815'/0'/0/1",
                    "m/1852'/1815'/0'/2/1000001",
                    nano_nav_show=[NavInsID.BOTH_CLICK] * 3 + [NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] * 2),
    DeriveAddressTestCase("base_address_pathkeyHash_unusual_account",
                    Testnet,
                    AddressType.BASE_PAYMENT_KEY_STAKE_KEY,
                    "m/1852'/1815'/101'/0/1",
                    "1d227aefa4b773149170885aadba30aab3127cc611ddbc4999def61c",
                    nano_nav_confirm=nav_inst_1,
                    nano_nav_show=[NavInsID.BOTH_CLICK] * 2 + [NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] + [NavInsID.RIGHT_CLICK] * 2 + [NavInsID.BOTH_CLICK] * 2),
    DeriveAddressTestCase("base_address_pathkeyHash_unusual_address_index",
                    Testnet,
                    AddressType.BASE_PAYMENT_KEY_STAKE_KEY,
                    "m/1852'/1815'/0'/0/1'",
                    "1d227aefa4b773149170885aadba30aab3127cc611ddbc4999def61c",
                    nano_nav_confirm=nav_inst_1,
                    nano_nav_show=[NavInsID.BOTH_CLICK] * 2 + [NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] + [NavInsID.RIGHT_CLICK] * 2 + [NavInsID.BOTH_CLICK] * 2),
    DeriveAddressTestCase("base_address_scriptHashpath_unusual_account",
                    Testnet, AddressType.BASE_PAYMENT_SCRIPT_STAKE_KEY,
                    "122a946b9ad3d2ddf029d3a828f0468aece76895f15c9efbd69b4277",
                    "m/1852'/1815'/200'/2/0",
                    nano_nav_confirm=nav_inst_2,
                    nano_nav_show=[NavInsID.BOTH_CLICK] + [NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] * 2 + [NavInsID.RIGHT_CLICK] * 2 + [NavInsID.BOTH_CLICK] * 2),
    DeriveAddressTestCase("base_address_pathscriptHash_unusual_account",
                    Testnet,
                    AddressType.BASE_PAYMENT_KEY_STAKE_SCRIPT,
                    "m/1852'/1815'/101'/0/1",
                    "122a946b9ad3d2ddf029d3a828f0468aece76895f15c9efbd69b4277",
                    nano_nav_confirm=nav_inst_1,
                    nano_nav_show=[NavInsID.BOTH_CLICK] * 2 + [NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] + [NavInsID.RIGHT_CLICK] * 2 + [NavInsID.BOTH_CLICK] * 2),
    DeriveAddressTestCase("base_address_pathscriptHash_unusual_address_index",
                    Testnet,
                    AddressType.BASE_PAYMENT_KEY_STAKE_SCRIPT,
                    "m/1852'/1815'/0'/0/1'",
                    "122a946b9ad3d2ddf029d3a828f0468aece76895f15c9efbd69b4277",
                    nano_nav_confirm=nav_inst_1,
                    nano_nav_show=[NavInsID.BOTH_CLICK] * 2 + [NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] + [NavInsID.RIGHT_CLICK] * 2 + [NavInsID.BOTH_CLICK] * 2),
    DeriveAddressTestCase("pointer_address_unusual_account",
                    Testnet,
                    AddressType.POINTER_KEY,
                    "m/1852'/1815'/1000'/0/1",
                    pointer_to_str(1, 0, 0),
                    nano_nav_show=[NavInsID.BOTH_CLICK] * 3 + [NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] * 2),
    DeriveAddressTestCase("pointer_address_unusual_address_index",
                    Testnet,
                    AddressType.POINTER_KEY,
                    "m/1852'/1815'/0'/0/1'",
                    pointer_to_str(0, 7, 0),
                    nano_nav_show=[NavInsID.BOTH_CLICK] * 3 + [NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] * 2),
    DeriveAddressTestCase("reward_multidelegation_unusual_account",
                    Testnet,
                    AddressType.REWARD_KEY,
                    "",
                    "m/1852'/1815'/101'/2/1",
                    nano_nav_show=[NavInsID.BOTH_CLICK] * 2 + [NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] * 2),
    DeriveAddressTestCase("reward_multidelegation_unusual_index",
                    Testnet,
                    AddressType.REWARD_KEY,
                    "",
                    "m/1852'/1815'/0'/2/20000000",
                    nano_nav_show=[NavInsID.BOTH_CLICK] * 2 + [NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] * 2),
    DeriveAddressTestCase("reward_path_unusual_account",
                    FakeNet,
                    AddressType.REWARD_KEY,
                    "",
                    "m/1852'/1815'/300'/2/0",
                    nano_nav_show=[NavInsID.BOTH_CLICK] * 2 + [NavInsID.RIGHT_CLICK] + [NavInsID.BOTH_CLICK] * 2),
]
