ERRORS = {
    "SW_DENY":                      0x6985,
    "SW_WRONG_P1P2":                0x6A86,
    "SW_WRONG_DATA_LENGTH":         0x6A87,
    "SW_INS_NOT_SUPPORTED":         0x6D00,
    "SW_CLA_NOT_SUPPORTED":         0x6E00,
    "SW_WRONG_RESPONSE_LENGTH":     0xB000,
    "SW_DISPLAY_BIP32_PATH_FAIL":   0xB001,
    "SW_DISPLAY_ADDRESS_FAIL":      0xB002,
    "SW_DISPLAY_AMOUNT_FAIL":       0xB003,
    "SW_WRONG_TX_LENGTH":           0xB004,
    "SW_TX_PARSING_FAIL":           0xB005,
    "SW_TX_HASH_FAIL":              0xB006,
    "SW_BAD_STATE":                 0xB007,
    "SW_SIGNATURE_FAIL":            0xB008,
}
