#pragma once

// SDK status words (ISO 7816-4 standard)
#include <status_words.h>

// Cardano app-specific status words (0xB0XX range)
// TODO this perhaps needs to be redesigned, not sure if the range is valid according to the ISO above
#define SWO_DISPLAY_BIP32_PATH_FAIL 0xB001
#define SWO_DISPLAY_ADDRESS_FAIL 0xB002
#define SWO_DISPLAY_AMOUNT_FAIL 0xB003
#define SWO_INVALID_TX_LENGTH 0xB004
#define SWO_TX_PARSING_FAIL 0xB005
#define SWO_BAD_STATE 0xB007
#define SWO_SIGNATURE_FAIL 0xB008
#define SWO_OPCERT_PARSING_FAIL 0xB011
#define SWO_INVALID_OPCERT_LENGTH 0xB012
#define SWO_BIP44_PATH_PARSING_FAIL 0xB013
#define SWO_TX_PARSING_FAIL_INPUTS 0xB020
#define SWO_TX_PARSING_FAIL_OUTPUTS 0xB021
#define SWO_TX_PARSING_FAIL_FEE 0xB022
#define SWO_TX_PARSING_FAIL_TTL 0xB023
#define SWO_TX_PARSING_FAIL_INCLUSION_FLAG 0xB024
#define SWO_INVALID_NETWORK_ID 0xB025
#define SWO_TX_PARSING_FAIL_VALIDITY_INTERVAL_START 0xB026
#define SWO_TX_PARSING_FAIL_BUFFER_NOT_FULLY_CONSUMED 0xB027
#define SWO_INVALID_PROTOCOL_MAGIC 0xB028
#define SWO_TX_PARSING_FAIL_CERTIFICATES 0xB029
#define SWO_TX_PARSING_FAIL_WITHDRAWALS 0xB02A
#define SWO_TX_PARSING_FAIL_MINT 0xB02B
