#pragma once

// SDK status words (ISO 7816-4 standard)
#include <status_words.h>

// Cardano app-specific status words (0xB0XX range)
// TODO this perhaps needs to be redesigned, not sure if the range is valid according to the ISO above
#define SWO_INVALID_TX_LENGTH 0xB004
#define SWO_TX_PARSING_FAIL 0xB005
#define SWO_BAD_STATE 0xB007
#define SWO_SIGNATURE_FAIL 0xB008
#define SWO_OPCERT_PARSING_FAIL_KES_KEY 0xB010
#define SWO_OPCERT_PARSING_FAIL_KES_PERIOD 0xB011
#define SWO_OPCERT_PARSING_FAIL_ISSUE_COUNTER 0xB012
#define SWO_OPCERT_PARSING_FAIL_POOL_KEY_PATH 0xB013
#define SWO_INVALID_OPCERT_LENGTH 0xB014
#define SWO_BIP44_PATH_PARSING_FAIL 0xB015
#define SWO_TX_PARSING_FAIL_INPUTS 0xB020
#define SWO_TX_PARSING_FAIL_OUTPUTS 0xB021
#define SWO_TX_PARSING_FAIL_FEE 0xB022
#define SWO_TX_PARSING_FAIL_TTL 0xB023
#define SWO_TX_PARSING_FAIL_INCLUSION_FLAG 0xB024
#define SWO_INVALID_NETWORK_ID 0xB025
#define SWO_TX_PARSING_FAIL_VALIDITY_INTERVAL_START 0xB026
#define SWO_TX_PARSING_FAIL_BUFFER_NOT_FULLY_CONSUMED 0xB027
#define SWO_INVALID_PROTOCOL_MAGIC 0xB028
#define SWO_TX_PARSING_FAIL_CERTIFICATES 0xB029
#define SWO_TX_PARSING_FAIL_WITHDRAWALS 0xB02A
#define SWO_TX_PARSING_FAIL_MINT 0xB02B
#define SWO_TX_PARSING_FAIL_SCRIPT_DATA_HASH 0xB02F
#define SWO_TX_PARSING_FAIL_COLLATERAL_INPUTS 0xB030
#define SWO_TX_PARSING_FAIL_REQUIRED_SIGNERS 0xB031
#define SWO_TX_PARSING_FAIL_COLLATERAL_OUTPUT 0xB032
#define SWO_TX_PARSING_FAIL_TOTAL_COLLATERAL 0xB033
#define SWO_TX_PARSING_FAIL_REFERENCE_INPUTS 0xB034
#define SWO_TX_PARSING_FAIL_CANONICAL_ORDER 0xB035
#define SWO_TX_PARSING_FAIL_TREASURY 0xB02C
#define SWO_TX_PARSING_FAIL_DONATION 0xB02D
#define SWO_TX_PARSING_FAIL_VOTING_PROCEDURES 0xB02E
