name: Call build and tests entry point

# This workflow will call the companion workflow reusable_build_and_functional_tests.yml of this repository
#
# The build part of this workflow is mandatory, this ensures that the app will be deployable in the Ledger App Store.
# While the test part of this workflow is optional, having functional testing on your application is mandatory and this workflow and
# tooling environment is meant to be easy to use and adapt after forking your application

on:
  workflow_dispatch:
    inputs:
      golden_run:
        type: choice
        required: true
        default: 'Raise an error (default)'
        description: CI behavior if the test snapshots are different than expected.
        options:
          - 'Raise an error (default)'
          - 'Open a PR'
  push:
    branches:
      - master
      - main
      - develop
  pull_request:

jobs:
  job_call_build_and_test:
    name: Build and test
    uses: ./.github/workflows/reusable_build_and_functional_tests.yml
    with:
      branch: ${{ github.ref }}
      regenerate_snapshots: ${{ inputs.golden_run == 'Open a PR' }}
