name: Callable Swap Functional tests

on:
  workflow_call:
    inputs:
      app_build_artifact:
        required: true
        type: string
      exchange_build_artifact:
        required: true
        type: string
      ethereum_build_artifact:
        required: true
        type: string
      regenerate_snapshots:
        required: false
        default: false
        type: boolean
jobs:
  # This job runs the swap functional tests using the reusable workflow
  ragger_tests_swap:
    name: Run swap ragger tests using the reusable workflow
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_ragger_tests.yml@y333/manage_several_pytest_directories
    with:
      download_app_binaries_artifact: ${{ inputs.app_build_artifact }}
      additional_app_binaries_artifact: ${{ inputs.exchange_build_artifact }}
      additional_app_binaries_artifact_dir: "tests/swap/main_app/exchange/build"
      lib_binaries_artifact: ${{ inputs.ethereum_build_artifact }}
      test_dir: "tests/swap"
      regenerate_snapshots: ${{ inputs.regenerate_snapshots }}
