name: Callable Swap Functional tests

on:
  workflow_call:
    inputs:
      branch_for_app:
        required: false
        default: 'develop'
        type: string
      branch_for_exchange:
        required: false
        default: 'develop'
        type: string
      regenerate_snapshots:
        required: false
        default: false
        type: boolean
jobs:
  build_application:
    name: Build application using the reusable workflow
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_build.yml@y333/manage_several_pytest_directories
    with:
      app_repository: 'LedgerHQ/app-boilerplate'
      app_branch_name: '${{ inputs.branch_for_app }}'
      upload_app_binaries_artifact: "compiled_app_binaries_bis"

  build_exchange:
    name: Build Exchange app using the reusable workflow
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_build.yml@y333/manage_several_pytest_directories
    with:
      app_repository: 'LedgerHQ/app-exchange'
      app_branch_name: '${{ inputs.branch_for_exchange }}'
      upload_app_binaries_artifact: "compiled_exchange_binaries"
      use_case: 'dbg_full_replay'

  build_ethereum:
    name: Build Ethereum app using the reusable workflow
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_build.yml@y333/manage_several_pytest_directories
    with:
      app_repository: 'LedgerHQ/app-ethereum'
      app_branch_name: 'develop'
      upload_app_binaries_artifact: "compiled_ethereum_binaries"
      upload_as_lib_artifact: "ethereum_"
      use_case: 'use_test_keys'

  # This job runs the swap functional tests using the reusable workflow
  ragger_tests_swap:
    name: Run swap ragger tests using the reusable workflow
    needs: [build_application, build_exchange, build_ethereum]
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_ragger_tests.yml@y333/manage_several_pytest_directories
    with:
      download_app_binaries_artifact: "compiled_app_binaries_bis"
      additional_app_binaries_artifact: "compiled_exchange_binaries"
      additional_app_binaries_artifact_dir: "tests/swap/main_app/exchange/build"
      lib_binaries_artifact: "compiled_ethereum_binaries"
      test_dir: "tests/swap"
      regenerate_snapshots: ${{ inputs.regenerate_snapshots }}
