name: Generate project documentation

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:

jobs:
  job_generate_doc:
    name: Generate project documentation
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_doc_generation.yml@v1
