name: Swap functional tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:

jobs:
  job_functional_tests:
    uses: LedgerHQ/app-exchange/.github/workflows/reusable_swap_functional_tests_v2.yml@y333/exchange_client_package
    with:
      branch_for_app: ${{ github.ref }}
      repo_for_app: ${{ github.repository }}
